UPDATE produto SET preco = 24.90 WHERE idProduto = 1;
UPDATE usuario SET nome = "Lucas Souza" WHERE idUsuario = 1;
UPDATE endereco SET cidade = "Jaboatão" WHERE Usuario_idUsuario = 2;
UPDATE carrinho SET statusCarrinho = "Finalizado" WHERE idCarrinho = 3;
UPDATE pedido SET statusPedido = "Cancelado" WHERE idPedido = 2;
UPDATE cliente SET CPF = "123.123.123-12" WHERE Usuario_idUsuario = 5;
UPDATE vendedor SET tipo = "Empreendedor" WHERE Usuario_idUsuario = 6;
UPDATE loja SET nome = "Ecovidas Sustentável" WHERE idLoja = 3;
UPDATE categoria SET nome = "Higiene Natural" WHERE idCategoria = 2;
UPDATE produto SET estoque = 15 WHERE idProduto = 4;
DELETE FROM itemcarrinho WHERE Produto_idProduto = 5;
DELETE FROM carrinho WHERE idCarrinho = 10;
DELETE FROM formapag WHERE idFormaPag = 3;
DELETE FROM usuarioConteudo WHERE Usuario_idUsuario = 4 AND ConteudoEducativo_idConteudoEducativo = 2;
DELETE FROM feedback WHERE idFeedback = 6;
DELETE FROM produto_possui_categoria WHERE Produto_idProduto = 3 AND Categoria_idCategoria = 2;
DELETE FROM produto_possui_tiposustentavel WHERE Produto_idProduto = 2 AND TipoSustentavel_idTipoSustentavel = 1;
DELETE FROM usuario WHERE Usuario_idUsuario = 8;
DELETE FROM loja WHERE idLoja = 8;
DELETE FROM endereco WHERE Usuario_idUsuario = 10;
